#!/bin/bash
echo ""
echo "========================================"
echo "   FiveM HUD Installation Fix"
echo "========================================"
echo ""
echo "ERROR: Folder named [HUD] causes warnings"
echo ""
echo "FIX: Rename folder to: greenzone420_hud"
echo "     (NO brackets!)"
echo ""
echo "Then in server.cfg use:"
echo "     ensure greenzone420_hud"
echo ""
echo "========================================"
echo ""
